---
title: "p8105_hw5_eb3516"
author: "Liz Bekerman"
date: "2023-11-16"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)

options(
  ggplot2.continuous.colour="viridis",
  ggplot2.continuous.fill="viridis"
)

scale_colour_discrete=scale_colour_viridis_d
scale_fill_discrete=scale_fill_viridis_d
```


## Question 2
```{r}
file_names= list.files(path= "./data/study", full.names=TRUE)
import=function(path){
    df=read_csv(path) |>
      janitor::clean_names() |>
      mutate(ID=path) |>
      separate(ID, into=c("folder", "arm", "e2", "subject", "csv"), sep=c(5,8,9,11)) |>
      arrange(arm, subject) |>
    pivot_longer(week1:week8,
                  names_to="week",
                 values_to="value") |>
      separate(week, into=c("W", "Week_Num"), sep="_")
}
clean_df=map(file_names, import) |>
               bind_rows()
```  

```{r}
clean_df |>
    ggplot(aes(x=Week_Num, y=value, color=subject))+geom_line()
```

## Question 3
```{r}
sim=function(mu) {
  data=tibble(
    x=rnorm(n=30,mean=mu,sd=5)
  )

  output=data |>
    t.test() |>
    broom::tidy() |>
    select(estimate, p.value) |>
    rename(mu_hat=estimate, p_value=p.value)
}
```

